package mypack.Entity;
// Generated Nov 13, 2016 12:44:40 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String username;
	private String password;
	private Date registerTime;

	public Users() {
	}

	public Users(String username) {
		this.username = username;
	}

	public Users(String username, String password, Date registerTime) {
		this.username = username;
		this.password = password;
		this.registerTime = registerTime;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

}
