package mypack.Entity;
// Generated Oct 8, 2016 9:55:11 PM by Hibernate Tools 4.0.0

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private UsersId id;

	public Users() {
	}

	public Users(UsersId id) {
		this.id = id;
	}

	public UsersId getId() {
		return this.id;
	}

	public void setId(UsersId id) {
		this.id = id;
	}

}
