package mypack.Entity;
// Generated Oct 8, 2016 9:55:11 PM by Hibernate Tools 4.0.0

import java.util.*;

/**
 * UsersId generated by hbm2java
 */
public class UsersId implements java.io.Serializable {

	private String name;
	private String password;
	private Date registerTime;

	public UsersId() {
	}

	public UsersId(String name, String password, Date registerTime) {
		this.name = name;
		this.password = password;
		this.registerTime = registerTime;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersId))
			return false;
		UsersId castOther = (UsersId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
				&& this.getName().equals(castOther.getName())))
				&& ((this.getPassword() == castOther.getPassword()) || (this.getPassword() != null
						&& castOther.getPassword() != null && this.getPassword().equals(castOther.getPassword())))
				&& ((this.getRegisterTime() == castOther.getRegisterTime())
						|| (this.getRegisterTime() != null && castOther.getRegisterTime() != null
								&& this.getRegisterTime().equals(castOther.getRegisterTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getPassword() == null ? 0 : this.getPassword().hashCode());
		result = 37 * result + (getRegisterTime() == null ? 0 : this.getRegisterTime().hashCode());
		return result;
	}

}
